### ISSUE TITLE
Specify default encoding when talking to database

### ISSUE THREAD

**Issue by tristanbes** [manala/ansible-roles#105]
Hello,

I'm trying to know where to add in my `app.yml` 2 lines of config for MariaDB conf (basically put in my.cnf)

```
[mysqld]
collation-server = utf8mb4_unicode_ci 
character-set-server = utf8mb4     
```

Thank you for your help :-)

**Comment by nervo** [comment]
Hi @tristanbes , you can use `manala_mysql_configs` (mapped to `mysql_configs` in your app.yml) just like in the readme there: https://github.com/manala/ansible-roles/tree/master/manala.mysql

**Comment by tristanbes** [comment]
Thanks !
