### ISSUE TITLE
oauth2-proxy incorrectly assumes the binary is available as a Debian package

### ISSUE THREAD

**Issue by danrough** [manala/ansible-roles#138]
In https://github.com/manala/ansible-roles/blob/master/manala.oauth2-proxy/tasks/install.yml the oauth2-proxy role attempts to install a debian package using apt. The oauth2-proxy binary isn't available as a debian package. The project's homepage says that there are two ways to install the package, either by downloading a pre-built binary or by downloading the source and compiling locally, https://github.com/bitly/oauth2_proxy#installation

**Comment by nervo** [comment]
Yep ! As spotted in the role's README (https://github.com/manala/ansible-roles/tree/master/manala.oauth2-proxy#requirements), we (manala) also provides the debian package itself on our debian repository.
Fyi, you can find the sources here: https://github.com/manala/debian-packages/tree/master/oauth2-proxy

If you have any ideas of how we can make this part of documentation clearer, please, tell us :)

**Comment by danrough** [comment]
Really sorry to have bothered you with this one - I don't understand how I missed that bit of the documentation :(

**Comment by nervo** [comment]
You're welcome :)
