### ISSUE TITLE
phpmyadmin version update and deprecations with php 7.2

### ISSUE THREAD

**Issue by mediafigaro** [manala/ansible-roles#153]
Hello & thanks, phpmyadmin version is 4.6.6deb4 and there are some bugs because of new features with php 7.2. Is it possible to upgrade phpmyadmin to > 4.7.4 (latest 4.7.7) ?

> phpmyadmin 4.7.4 is supposed to have "Fixed several compatibility issues with PHP 7.2" https://www.phpmyadmin.net/news/2017/8/24/phpmyadmin-474-released/

**Comment by nervo** [comment]
Hello, as spotted in the README (right here: https://github.com/manala/ansible-roles/tree/master/manala.phpmyadmin#requirements) `This role is made to work with the manala phpmyadmin debian package` :)

**Comment by mediafigaro** [comment]
thanks, - manala.apt  (+) - manala.phpmyadmin, but do you know what would be configured ? Any tutorial ? :)

**Comment by nervo** [comment]
@mediafigaro what do you mean by "what would be configured" ? At which level, apt ? phpmyadmin ?

**Comment by nervo** [comment]
ping @mediafigaro

**Comment by gfaivre** [comment]
Dead thread. Closing.
