### ISSUE TITLE
How to upgrade a PHP version

### ISSUE THREAD

**Issue by tristanbes** [manala/ansible-roles#193]
Hey there,

Is there a built-in way to uninstall old PHP in case of an upgrade ?

**Comment by nervo** [comment]
No built-in way, sorry :(
We tried hard, but finally gave up.

Something important to take into account, is the debian repository you use for php 7.1
Using sury for 7.1, upgrade to 7.2 is trivial.
But using dotdeb for 7.1, upgrade to 7.2 is an another issue...

**Comment by tristanbes** [comment]
Yes we use sury both both. upgrade went well. I uninstalled php after.
Thanks

**Comment by nervo** [comment]
Can we consider this issue as closed ?
