### ISSUE TITLE
Support MySQL 8.0

### ISSUE THREAD

**Issue by tristanbes** [manala/ansible-roles#241]
Hello, 

MySQL 8.0 has been released on April 2018. It would be awesome of it would be possible to install it with manala.

**Comment by nervo** [comment]
Yep, it's on the roadmap :)

**Comment by Kocal** [comment]
For information, there is #349  which allows you to install MySQL 8.0 but it looks like its support is not official. 

I'm facing an issue while creating users with MySQL 8.0:
![image](https://user-images.githubusercontent.com/2103975/101897124-59159d80-3baa-11eb-9cdb-c7bad39136d5.png)

While everything works fine with MySQL 5.7: 
![image](https://user-images.githubusercontent.com/2103975/101897197-764a6c00-3baa-11eb-99e1-7547877531b4.png)

Note that I am able to connect to the database through `sudo mysql -u root`, so maybe https://github.com/manala/ansible-roles/blob/master/roles/mysql/tasks/users.yml should be executed with `become_user: root`?

**Comment by nervo** [comment]
Closed by https://github.com/manala/ansible-roles/pull/510

**Comment by Kocal** [comment]
Hi, I'm not sure to understand how #510 (for PHP 8.0) have fixed this issue (for MySQL 8.0)

**Comment by nervo** [comment]
Oh god..... mysql !== php :)

**Comment by nervo** [comment]
Indirectly solved by https://github.com/manala/ansible-roles/pull/528
Implemented in elao.app recipe https://github.com/manala/manala-recipes/pull/94

**Comment by Kocal** [comment]
Oh alright, thanks! :)
