### ISSUE TITLE
Where are cron jobs added with manala.cron role?

### ISSUE THREAD

**Issue by cpxPratik** [manala/ansible-roles#284]
After running the ansible role with no error, `crontab -l` shows no jobs, says `no crontab for root`. I have checked on `/etc/cron.d`, `/etc/cron.daily` too.

**Comment by nervo** [comment]
Hi @cpxPratik could you provide your playbook so that we can help you ?

**Comment by cpxPratik** [comment]
Sorry, mistake on my part. Cron job is created on `/etc/cron.d`, but `crontab -l` still says `no crontab for root`.
