### ISSUE TITLE
Can't use XDebug with PHP 7.3

### ISSUE THREAD

**Issue by Kocal** [manala/ansible-roles#305]
Hi, I'm facing an issue while trying to use XDebug with PHP 7.3 (it worked fine with PHP 7.2).

Just after running `manala_php_xdebug on`:
![502 bad gateway - google chrome_282](https://user-images.githubusercontent.com/2103975/53721211-eb7bff80-3e62-11e9-8330-4b96324760e7.png)

The Nginx configuration seems to be valid:
![selection_283](https://user-images.githubusercontent.com/2103975/53721248-06e70a80-3e63-11e9-88ca-cef3e21f1c9b.png)

Nginx and PHP-FPM logs:
![app yprox -srv-app_285](https://user-images.githubusercontent.com/2103975/53721467-9987a980-3e63-11e9-9c5f-736341198cd3.png)

If I run `manala_php_xdebug off`, everything goes fine.

**Comment by Kocal** [comment]
Well, in fact I found how to fix the issue while I was writing the previous post, but I prefer keep a trace here if someone has the same issue.

It happened to laravel/valet too https://github.com/laravel/valet/issues/685 and it has been fixed in https://github.com/xdebug/xdebug/pull/438.

A simple `sudo apt update`, `sudo apt upgrade`, and `sudo service php7.3-fpm` and Xdebug finally works:
![selection_286](https://user-images.githubusercontent.com/2103975/53722342-9c839980-3e65-11e9-8ac5-5ace8c4f5b9d.png)

**Comment by nervo** [comment]
Good to know, thx @Kocal !
