### ISSUE TITLE
[apt] Debian Buster not supported?

### ISSUE THREAD

**Issue by roedie** [manala/ansible-roles#357]
Hi,

When runing my playbook against a freshly installed Debian Buster system I get the following error:

```
TASK [manala.apt : preferences > Templates presents] 
task path: /Users/sander/.ansible/roles/manala.apt/tasks/preferences.yml:15
fatal: [kvm-test]: FAILED! => {
    "msg": "'dict object' has no attribute 'buster'"
}
```

When running against a Stretch host everyting is fine.

Ansible 2.8.2
Python 3.7.4

Is this a bug or am I doing something wrong here?

**Comment by nervo** [comment]
Hi @roedie thanks for your interest, it's on the way :)

#359

**Comment by roedie** [comment]
Wicked, can't wait (-:

**Comment by nervo** [comment]
And it's done :)
