### ISSUE TITLE
Document that this is currently debian-only?

### ISSUE THREAD

**Issue by eis** [manala/ansible-roles#366]
I didn't find it mentioned anywhere, but it seems before something like https://github.com/manala/ansible-roles/pull/78 is merged, there is no e.g. CentOS support.

**Comment by hyvs** [comment]
You can find supported OS in roles metadata, see https://github.com/manala/ansible-roles/blob/master/manala.php/meta/main.yml#L14

We have no plan to support others distributions, but we are not against externals PR. (like #78)

**Comment by eis** [comment]
Could the supported operating systems be somehow documented outside source code as well?

It would to me sound reasonable to have them in the requirements section of the relevant [README.md ](https://github.com/manala/ansible-roles/blob/master/manala.cron/README.md), where they would get populated to [galaxy](https://galaxy.ansible.com/manala/cron). Without it, it's not possible to say from galaxy that these operating systems are requirements. Readme could at least say "one of the operating systems listed in the meta yml", and link to relevant file, for instance.

**Comment by eis** [comment]
I'm not sure how the galaxy system works in this regard, but for example manala.cron [is not tagged with debian](https://galaxy.ansible.com/search?keywords=cron&order_by=-relevance&page=1&deprecated=false) even though it is only (at least for now) for debian. Could the tagging be added?

**Comment by hyvs** [comment]
You can use filters in galaxy to match given distribution ; https://galaxy.ansible.com/search?keywords=cron&order_by=-relevance&page=1&platforms=ArchLinux <https://galaxy.ansible.com/search?keywords=cron&order_by=-relevance&page=1&platforms=ArchLinux>

And compatible distributions are displayed on galaxy role page :



Yves.
