### ISSUE TITLE
manala.php doesn't seem to support both PHP version

### ISSUE THREAD

**Issue by tristanbes** [manala/ansible-roles#4]
manala.php doesn't seem to support both PHP version

Or maybe it's not documented, but what about having `php5-fpm` && `php7-fpm` ? Is this supported by manala.php ?

Thanks.

**Comment by nervo** [comment]
Although it could be supported using sury php debian repository - now that minor versions like 7.0 and 7.1 are properly handled - it would be a real mess to handle it in the manala php role, sorry...
To be honest, soon or later, we will probably add an exclusive version flag to be sure one and only version is available.
