### ISSUE TITLE
[postgresql] version 12.2 is not available. 

### ISSUE THREAD

**Issue by DO1JLR** [manala/ansible-roles#414]
Hi
based on [the internet](https://www.postgresql.org/support/versioning/) the version 12.2 is the latest postgresql release.
```
TASK [postgresql : install > Packages]
*********************************************************************
fatal: [atlassian-database.wingcon.com]: FAILED! => changed=false 
  msg: No package matching 'postgresql-12.2' is available
```
Maybe it is a good idea to add the apt sources...:
https://www.postgresql.org/download/linux/debian/

tested on debian buster.

my config:
```
---
manala_postgresql_version: 12.2
```

**Comment by hyvs** [comment]
Versions `12` and `13` are available just put major version in `manala_postgresql_version`: 

```
---
manala_postgresql_version: 12
```
