### ISSUE TITLE
[Proftpd] users > home directories mode: 0600 missing +x

### ISSUE THREAD

**Issue by talset** [manala/ansible-roles#417]
With https://github.com/manala/ansible-role-proftpd/commit/1c87718ba93b650da9e85a656383a968bcab2a61#commitcomment-38961842

mode `600` is `r+w` but the `x` is missing, so users can't cross the directory.
Would be nice to have at least 700.

**Comment by nervo** [comment]
Hm, it seems thats it has been a bit quickly copy/pasted from user files permissions...  in https://github.com/manala/ansible-roles/commit/0219c82f97165bf3e7e74ce558574aaaf128a4e2
