### ISSUE TITLE
Tag a new release for PHP roles (and maybe others related packages)

### ISSUE THREAD

**Issue by Kocal** [manala/ansible-roles#550]
Hi :wave: 

I finally fixed my JSON extension issue (#548) but I can't go any further because a configuration file is not found:
![image](https://user-images.githubusercontent.com/2103975/113275974-a34c9700-92df-11eb-95ce-28beba11db8f.png)

and yeah there is no `8.0` config folder:
![image](https://user-images.githubusercontent.com/2103975/113276216-e7d83280-92df-11eb-9f82-555b83f4cdee.png)

It looks like roles updated in #510 has not been released on github/ansible galaxy:
- https://github.com/manala/ansible-role-php, latest tag is 2.0.7 from 26th Aug 2020
- https://github.com/manala/ansible-role-phpmyadmin, latest tag is 2.0.3 from 28th Aug 2020
- etc...

Is it possible to tag a new release?

Thanks!

**Comment by Kocal** [comment]
I had just seen this, on https://github.com/manala/ansible-role-php/blob/master/CHANGELOG.md the changelog is not the same than https://github.com/manala/ansible-roles/blob/master/roles/php/CHANGELOG.md

![image](https://user-images.githubusercontent.com/2103975/113277671-44881d00-92e1-11eb-9513-34a40b218c74.png)
vs
![image](https://user-images.githubusercontent.com/2103975/113277698-4b169480-92e1-11eb-8e46-dacd62f29374.png)

Maybe this is the problem? Subpackages are not updated anymore (and is this intentional?) 
Thanks!

**Comment by nervo** [comment]
Ok, we have just made a manual split :) Everythings should be allright now.

Sorry for the mess, it seems that few things gone wild during the switch from travis to github actions...

**Comment by Kocal** [comment]
No worries, happy this has been resolved quickly. Thanks! :)

**Comment by Kocal** [comment]
Hum in fact not really, the latest tag for php role is still 2.0.7

**Comment by nervo** [comment]
Damned, for each role, we have a related travis task to sync with ansible galaxy...

**Comment by nervo** [comment]
Can't you switch to manal 🧗 ? I can drive you if you want

**Comment by Kocal** [comment]
For sure that would be the easiest for both of us, but as you already know I have an issue with Redis (https://github.com/manala/manala-recipes/issues/125), another one with Docker (but I think I will disable it), and so I'm waiting for https://github.com/manala/manala-recipes/pull/123 👀 

I will give a last try tonight and tell you if I'm stuck again.
If needed, are you available tomorrow?

**Comment by nervo** [comment]
Yes i am :)
(you can ask tristan for my personnal contact)

**Comment by Kocal** [comment]
Nice! :)
I've aksed to him but I think he is sleeping right now. 

Here is my discord Kocal # 6542, I got two or three questions to ask you! :eyes:

**Comment by nervo** [comment]
nervo # 2217
It seems i can't add you as friend :)
