### ISSUE TITLE
PHP role, no release for php8

### ISSUE THREAD

**Issue by RomulusED69** [manala/ansible-roles#561]
Hi :hand: 
First of all, thank you for your different roles.

I wanted to use your php role to update my servers to php8 but I couldn't.
Indeed, there is no release tagged for the latest version of the master. I found this issue https://github.com/manala/ansible-roles/issues/550 but since April, there has been no evolution.

Do you think you can solve the problem one day?

Thank you for your attention.

**Comment by nervo** [comment]
Hello :)

don't worry, we have just decided to give up individual roles (too hard to maintained), and focus on a single ansible collection gathering all of them: https://galaxy.ansible.com/manala/roles
The work is not fully finalized, but already up. Feel free to give a try :)

**Comment by RomulusED69** [comment]
oh, ok, I understand. 
I will try to set up this with collection.

Thank you

**Comment by nervo** [comment]
You're welcome :)
