### ISSUE TITLE
Debian 11 bullseye support ? 

### ISSUE THREAD

**Issue by burnom** [manala/ansible-roles#566]
Hello,
thank you very much for sharing this ansible role.

Everything works fine for a Debian 10 client, but not for a Debian 11 client.

Are there any plans to support this version in the near future?

thanks in advance.

Bruno.

Here is the error reported : 

TASK [manala.apt : preferences > Templates presents] *******************************************************************************
Thursday 30 September 2021  17:38:57 +0200 (0:00:00.043)       0:00:03.912 ****
fatal: [srv.lan]: FAILED! => {"msg": "{'vim': 'vim*', 'git': 'git git-*', 'php': 'php-* php5-* php5.6-* php7.0-* php7.1-* php7.2-* php7.3-* php7.4-*', 'mysql': 'mysql* libmysql*', 'nginx': 'nginx*', 'ruby': 'ruby*', 'nodejs': 'nodejs*', 'rabbitmq': 'rabbitmq*', 'redis': 'redis*', 'logentries': 'logentries*', 'sensu': 'sensu*', 'haproxy': 'haproxy*', 'galera': 'galera*', 'grafana': 'grafana*', 'elasticsearch': 'elasticsearch*', 'postgresql': 'postgresql*', 'mongodb': 'mongodb*', 'keepalived': 'keepalived*', 'gitlab-ce': 'gitlab-ce*', 'phpmyadmin': 'phpmyadmin*', 'phppgadmin': 'phppgadmin*', 'docker': 'docker*', 'chrony': 'chrony*', 'backup-manager': 'backup-manager*', 'pam-ssh-agent-auth': 'libpam-ssh-agent-auth*', 'oauth2-proxy': 'oauth2-proxy*', 'cloud': 'cloud-init cloud-utils', 'mariadb': 'mariadb* libmariadb*', 'maxscale': 'maxscale*', 'influxdb': 'influxdb*', 'telegraf': 'telegraf*', 'thefuck': 'thefuck*', 'python-six': 'python-six*', 'htop': 'htop*', 'yarn': 'yarn*', 'openssh': 'openssh*', 'ansible': 'ansible*', 'openjdk': 'openjdk-* ca-certificates-java', 'linux': 'linux-base linux-image-* linux-headers-*', 'httpie': 'httpie*', 'certbot': 'certbot python-certbot python-acme python3-certbot python3-acme python-cryptography python-openssl python-setuptools python-pyasn1 python-pkg-resources', 'thumbor': 'thumbor python-libthumbor', 'mica': 'mica', 'sensu-go': 'sensu-go-*', 'ffmpeg': \"ffmpeg {{ { 'jessie': 'libavcodec56 libva1 libavdevice56 libavfilter5 libavformat56 libavresample2 libavutil54 libpostproc53 libswresample1 libswscale3', 'stretch': 'libavcodec57 libavdevice57 libavfilter6 libavformat57 libavresample3 libavutil55 libpostproc54 libswresample2 libswscale4', 'buster': 'libavcodec58 libavdevice58 libavfilter7 libavformat58 libavresample4 libavutil56 libpostproc55 libswresample3 libswscale5' }[ansible_distribution_release] }}\", 'glusterfs': 'glusterfs-*', 'newrelic-infra': 'newrelic-infra', 'filebeat': 'filebeat*'}: 'dict object' has no attribute 'bullseye'"}

**Comment by nervo** [comment]
Hi @burnom thx for your message ❤️ 

Yes, bullseye support is on its way ! See https://github.com/manala/ansible-roles/pull/558

As you can guess it won't be for tomorrow, but we work hard on the subject :)
