### ISSUE TITLE
MariaDB and Node latest version

### ISSUE THREAD

**Issue by Tom32i** [manala/ansible-roles#643]
Hi guys!

Would you consider supporting MariaDB [latest versions](https://mariadb.org/mariadb/all-releases/)?
We're suck on [10.6](https://github.com/manala/ansible-roles/blob/master/roles/apt/vars/main.yml#L101).

Same goes for Node [latest version](https://nodejs.org/fr/download/releases/). 
We're currently 3 version behind with [node 16](https://github.com/manala/ansible-roles/blob/master/roles/apt/vars/main.yml#L77).

I'd gladly make a PR for those updates. :)

**Comment by nervo** [comment]
-> https://github.com/manala/ansible-roles/pull/646
-> https://github.com/manala/ansible-roles/pull/648

Please, note that we only support LTS versions, in other words, nodejs 18 (https://endoflife.date/nodejs) and mariadb 10.11 (https://mariadb.org/download/?t=mariadb&p=mariadb&r=11.0.0)

**Comment by nervo** [comment]
Well, my bad, MariaDB 10.11 is still in rc...
Btw, being stucked on 10.6 means that we support the last avaialbale lts :)
