### ISSUE TITLE
Use ansible_facts

### ISSUE THREAD

**Issue by nervo** [manala/ansible-roles#678]
For instance:
- `ansible_distribution_release` -> `ansible_facts['distribution_release']`
- ...

Note: after that,, we could disable the related option, juste like here https://opendev.org/openstack/tripleo-common/commit/b9a164582ea64caa2dca3a4f4b1aad539a3ec5eb

**Comment by greedybro** [comment]
Done by @nervo 

https://github.com/manala/ansible-roles/commit/beefdfc4dfb45c77dd1f1a1075fa9cfede511faa
