### ISSUE TITLE
When will Bookworm be added?

### ISSUE THREAD

**Issue by roedie** [manala/ansible-roles#687]
Hi,

I just noticed Bookworm isn't supported in the 3.7.0 release. The release is based on commit 553f42f while Bookworm was added just one commit later in bbf2534.

**Comment by greedybro** [comment]
Hi ! 
Yeah we decided to delay as we want to put more new stuff in our next release, with bookworm support.
Expect it soon :D

**Comment by greedybro** [comment]
Hi ! It took us a long time, but the v4.0.0 of our roles is available, with official support for bookworm !
