### ISSUE TITLE
[Oh My Zsh] Switch to a new default based theme

### ISSUE THREAD

**Issue by nervo** [manala/ansible-roles#87]
Pygmalion is old, unmaintained, and buggy (see: https://github.com/robbyrussell/oh-my-zsh/issues/2317)

We *need* to choose another one.

https://github.com/robbyrussell/oh-my-zsh/wiki/themes

J'ai trouvé ca:
- https://zshthem.es/browse-zsh-themes/
- https://www.slant.co/topics/7553/~theme-for-oh-my-zsh
- https://hashnode.com/post/what-is-your-favorite-oh-my-zsh-theme-cirwop8fb0h0gdu53bc8rmeiv

**Comment by nervo** [comment]
Why not simply the default one, `robbyrussell`?

**Comment by benji07** [comment]
we didn't use the default because it's the default theme on our mac (and to avoid having the same theme inside the VM)

**Comment by nervo** [comment]
@benji07 👍

**Comment by ogizanagi** [comment]
See #88 to fix the issue. We don't have to change the theme \o/

**Comment by ogizanagi** [comment]
Closing as the original issue is fixed by #88
